### ISSUE TITLE
stable image doesn't support m1 macs

### ISSUE THREAD

**Issue by ReFil** [zmkfirmware/zmk-docker#126]
As hosted the stable image segfaults during compilation on apple silicon (arm) macs, the 3.0 branch image seems to work fine
https://github.com/KinesisCorporation/Adv360-Pro-ZMK/issues/37

**Comment by petejohanson** [comment]
I bet the `stable` tag got pointed to the x86_64 image, instead of the manifest... Let me dig

**Comment by petejohanson** [comment]
@ReFil This got auto closed, but I just finally pushed the tags to trigger the new `skopeo copy` version of our CI process. Looking now, I can see that the `stable` tag at https://hub.docker.com/r/zmkfirmware/zmk-build-arm/tags properly lists both architecture images.

Should be ready for testing now, both the `stable` tag and the `3.0` versioned image.
