### ISSUE TITLE
[Question] Is it trivial to modify the Dockerfile for a fork of zmk?

### ISSUE THREAD

**Issue by enoryw** [zmkfirmware/zmk-docker#163]
Is it trivial to modify the Dockerfile for a fork of zmk? I would like to use [this fork](https://github.com/moergo-sc/zmk) with docker but they don't provide a docker image and I'm not well versed in Docker. I figure not and it's not really relevant for this project anyway but just throwing it out there.

Thanks.

**Comment by caksoylar** [comment]
You shouldn't need to modify Dockerfile for most forks. Docker doesn't contain the zmk project itself, but its dependencies. Currently both `zmkfirmware/zmk` and `moergo-sc/zmk` depend on the same Zephyr version, so their dependencies should be compatible. Just follow https://zmk.dev/docs/development/setup/docker and clone from their fork on the first step.

**Comment by enoryw** [comment]
I was successful building via [Docker](https://github.com/jjangga0214/zmk-config-adv360-pro?tab=readme-ov-file#local-building-in-a-container) (I don't use VS Code which is the only way that's documented in ZMK). Do you happen to know if ZMK/Zephyr's west.yml can be modified to use a local/private repo? As I understand, after the Docker container is created, west initializes with [west.yml](https://github.com/moergo-sc/glove80-zmk-config-west/blob/main/config/west.yml) where it fetches the specified zmk repository (`moergo-sc/zmk`). But `moerg-sc/zmk` is not rebased to the latest zmk changes so I cloned and rebased it as a private repository accessible via SSH.

Requiring SSH access inside the container to fetch this is not ideal but I was thinking having the repository/source code locally and mounting it as a Docker volume makes better sense anyway (at least for dev) to avoid using bandwidth). But I'm not a programmer and was not successful reading the [docs](https://docs.zephyrproject.org/latest/develop/west/manifest.html) and tinkering with the settings. It seems to assume `remotes` are accessible via https:// or ssh:// but is there a way to use a local path to point to the repository/source code? "Fetch url" is not a local path?

I realize this is totally irrelevant to the project, so closing the issue.
