### ISSUE TITLE
Cannot pull published images because of missing manifest

### ISSUE THREAD

**Issue by plandevida** [zmkfirmware/zmk-docker#4]
Hi,

I tried to pull the zmk-dev-arm image but I couldn't because docker says there is a missing manifest for the image.

**Comment by petejohanson** [comment]
@plandevida We don't currently publish a `latest` tag, which may be why you hit this. Can you try with an explicit tag, e.g. `zmkfirmware/zmk-dev-arm:2.4` ?

**Comment by petejohanson** [comment]
Closing, re-open please if this doesn't solve this for you. Thanks!
