### ISSUE TITLE
Enhancement: include gdb installation by default

### ISSUE THREAD

**Issue by schengnz** [zmkfirmware/zmk-docker#7]
To simplify interactive debugging for native_posix build, it would be easier if gdb is added to the image by default

**Comment by mcrosson** [comment]
@schengnz which package(s) need to be installed for gdb support?

**Comment by innovaker** [comment]
@schengnz, if we put this in would be willing to help test please?

**Comment by schengnz** [comment]
YesSent from my Galaxy
-------- Original message --------From: innovaker ***@***.***> Date: 28/03/21  1:01 AM  (GMT+12:00) To: zmkfirmware/zmk-docker ***@***.***> Cc: schengnz ***@***.***>, Mention ***@***.***> Subject: Re: [zmkfirmware/zmk-docker] Enhancement: include gdb installation by default (#7) 
@schengnz, if we put this in would be willing to help test please?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-----------------------------------------------------------
Legal disclaimer: This e-mail message and accompanying data
is copyright of Innaworks Development Limited and contains
confidential information intended for a specific individual
and purpose. If you are not the intended recipient, please
notify the sender and delete this message immediately. Any
disclosure, copying or dissemination of this message (or
attachments), or the taking of any action based on it, is
strictly prohibited without the express permission of
Innaworks Development Limited.

**Comment by innovaker** [comment]
@schengnz, we'll soon be at a point where we can look into this further.

Are you on ZMK's Discord server?  If so, please message me so I know who you are 👍
